# Generated by Django 3.2.6 on 2021-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='receipts/'),
        ),
    ]
